### ISSUE TITLE
Import breaks when failing to create admin account

### ISSUE THREAD

**Issue by LauHypershop** [jellesiderius/mage-db-sync#14]
If you're importing a full DB and you already had an admin account there with the same email as you're using to set up one locally, you get an error:

```
In AdminAccount.php line 194:
                                                                               
  An existing user has the given email but different username. Username and email both need to match an existing user or both be new.
```

This is fine, but should be caught so that the rest of the script continues after that.

**Comment by jellesiderius** [comment]
Fixed in 0.5.0
