### ISSUE TITLE
Download placeholder images

### ISSUE THREAD

**Issue by LauHypershop** [jellesiderius/mage-db-sync#15]
Syncing down the entire media catalog could take a while, but some quick gains could be made just by downloading the product placeholder images.

**Comment by jellesiderius** [comment]
Moving issue to: https://github.com/jellesiderius/mage-db-sync/issues/3

**Comment by LauHypershop** [comment]
New idea: most stores have custom product placeholder images configured. If these are NOT downloaded, just dropping those rows from the config table is enough to fall back to default Magento placeholder images.
