### ISSUE TITLE
Unable to sync from production to Local development environment

### ISSUE THREAD

**Issue by anees-netable** [jellesiderius/mage-db-sync#21]
Hi

Installed the latest mage-db-sync 

Configured the production.json like below

![2022-10-18_01-06](https://user-images.githubusercontent.com/105837015/196198921-f8d1e536-6194-4751-90a3-7a290276d66e.png)

Failed on this step
 Downloading Magento database to localhost

![2022-10-18_01-09](https://user-images.githubusercontent.com/105837015/196199145-184a1502-4b55-4222-adeb-f1a6c5db8c70.png)

Please help me to resolve this issue

**Comment by jellesiderius** [comment]
Hi @anees-netable,

What happens when you try and run the rsync command by yourself through CLI? Try resolve that issue first, it seems like your public key is being denied.

**Comment by anees-netable** [comment]
Hi Jelle,

As you can see executing this command on the local development server has connected to the production server using the SSH Key and took the database dump

Why it is unable to download to the same local development server

I hope you understood my question

**Comment by jellesiderius** [comment]
Can you try running the rsync command by yourself to see what happens? Just copy and paste it to your CLI and try running it. I can't really see what is happening, is rsync installed?

**Comment by anees-netable** [comment]
Hi Jelle,

Bellow command executed to import the file from the production server to local

rsync -avz -e "ssh -p 1609 -o StrictHostKeyChecking=no" ubuntu@IPADDRESS:~/databasefileproduction.sql /var/www/html/mydomain/public_html243

Missing Key on above command. Please let me know what i need to change  on the configuration to include the PEM file like below

rsync -avz -e "ssh -i /secureFolder/MyProject.pem -p 1609 -o StrictHostKeyChecking=no" ubuntu@IPADDRESS:~/databasefileproduction.sql /var/www/html/mydomain/public_html243

Also, I defined the key here 

**/config/settings.json which was used to connect to the production server and prepared a dump** 

Kind Regards,
Syed

**Comment by jellesiderius** [comment]
If you run the command by yourself on a CLI, what does it output? You should be able to run the command and access the server with rsync like that.

**Comment by anees-netable** [comment]
Hi Jelle,

It says Permission error on the public key as there is no pem key defined on this command

This is the command generated by Mage db Sync

**command 1** : Generated by Mage db sync
rsync -avz -e "ssh -p 1609 -o StrictHostKeyChecking=no" ubuntu@IPADDRESS:~/databasefileproduction.sql /var/www/html/mydomain/public_html243


**command 2** :This is the command required to make it work

rsync -avz -e "ssh -i /secureFolder/MyProject.pem -p 1609 -o StrictHostKeyChecking=no" ubuntu@IPADDRESS:~/databasefileproduction.sql /var/www/html/mydomain/public_html243

You can see the difference

**Comment by jellesiderius** [comment]
Hmm, this is not yet implemented into mage-db-sync. What it currently does is, it searches for your homedir/.ssh/id_rsa as key, it does not support .pem files yet.

Are you using a different .pem file per project? Or is this a global file for you?

**Comment by anees-netable** [comment]
Hi Jelle,

I am using different pem files per project

**Comment by anees-netable** [comment]
Hi Jelle,

Just to test, I removed the current homedir/.ssh/id_rsa  and replaced with /secureFolder/MyProject.pem and also set the permission as 0400.

Still didn't work, tried with different file permission as well

**Comment by anees-netable** [comment]
Hi Jelle,

Do you have any plans to implement this functionality?

**Comment by jellesiderius** [comment]
Currently not. Mage-db-sync mainly supports ssh keys with OpenSSH. Maybe later if the request is higher, if you'd like, you can add a PR with this functionality.
